### ISSUE TITLE
Kivymd 2.*.*

### ISSUE THREAD

**Issue by SergShulga** [Novfensec/KvDeveloper#2]
What about support for kivymd 2.*?
As far as I know, the standard template MVC for this version is not assembled normally.

**Comment by Novfensec** [comment]
Please describe your issue in detail with commands and error logs you got.

I am currently focusing on creating templates with stable version releases of kivy and kivymd available on pypi, but there is no specific version support specified for kivymd releases to use KvDeveloper. Minimum requirements for this cli would be updated in the [READEME.md](https://github.com/Novfensec/kvdeveloper/blob/main/README.md) file.

**Comment by Novfensec** [comment]
A new version is released with bug fixes and improvements. Drop a comment if you still have issues using this cli.

**Comment by SergShulga** [comment]
O, thanks! I'll try it tomorrow!
